---
title: "Data e hora"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading data}
bikeurl <- "https://s3.amazonaws.com/tripdata/201902-citibike-tripdata.csv.zip"
unzippedfile <- "201902-citibike-tripdata.csv"
if (!file.exists(unzippedfile))
{
  destfile <- "bikesfev.csv.zip"
  if (!file.exists(destfile))
  {
    # here I had first to install curl on Ubuntu
    download.file(bikeurl, destfile = destfile, method = "curl")
    downloadtime <- date()
  }
  unzip(destfile)
}
dadosbike <- read.csv(unzippedfile)
```

Separando as colunas em data/hora

```{r tidying data}
library(tidyr)
dadosbike <- separate(dadosbike, starttime, c("startymd", "starthms"), sep = " ")
dadosbike <- separate(dadosbike, stoptime, c("stopymd", "stophms"), sep = " ")

class(dadosbike$starthms)
class(dadosbike$stophms)

library(lubridate)

head(dadosbike$starthms)
dadosbike$starthms <- hms(dadosbike$starthms)
head(dadosbike$starthms)

head(dadosbike$stophms)
dadosbike$stophms <- hms(dadosbike$stophms)
head(dadosbike$stophms)

head(hour(dadosbike$stophms))
head(minute(dadosbike$stophms))
head(second(dadosbike$stophms))
```